# Generated by Django 5.0.6 on 2024-05-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='type',
        ),
    ]
