# Generated by Django 5.0.6 on 2024-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0002_remove_usermodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date_create',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
